# These warnings are generated by `use Jido.AI.Agent` in
# AllbertAssist.Agents.IntentAgent. Keep this list narrow so Dialyzer remains a
# milestone gate for warnings from Allbert-owned code.
[
  {"lib/allbert_assist/agents/intent_agent.ex",
   "Type specification for __agent_metadata__ is a supertype of the success typing."},
  {"lib/allbert_assist/agents/intent_agent.ex",
   "Type specification for actions is a supertype of the success typing."},
  {"lib/allbert_assist/agents/intent_agent.ex",
   "Type specification for signal_routes is a supertype of the success typing."},
  {"lib/allbert_assist/agents/intent_agent.ex",
   "The type specification is missing types returned by AllbertAssist.Agents.IntentAgent.validate/2."}
]
